name: PipelineFlask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-crddqnrtq21c73d2d5ag
        api-key: rnd_IcbrR2EIFa6apZawYZdu2bdNApCv

    - name: Deploy no EC2 -AWS
      run: |
            echo "Conectando no EC2"
            echo "${{secrets.secret_aws}}" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-54-80-241-87.compute-1.amazonaws.com "
                   cd POC/;git pull;./python ./example.py"
